language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
  licenses:
    - android-sdk-license-5be876d5

branches:
  only:
    - master
    - android_develop

jdk: openjdk7

notifications:
  email: false

before_install:
  - git clone https://github.com/SujithVadakkepat/sdk-common.git
  - git clone https://github.com/SujithVadakkepat/sdk-render.git
  
install: gradle clean build

script: gradle check
